FROM php:8.2-apache

ARG UID=1000
ARG GID=1000

RUN usermod -u ${UID} www-data
RUN groupmod -g ${GID} www-data

COPY Docker/Dev/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN apt-get update \
    && apt-get install -y unzip git libzip-dev libpng-dev nano \
    && docker-php-ext-install pdo pdo_mysql zip gd \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN a2enmod rewrite


WORKDIR /var/www

COPY ./App ./App
COPY ./Public ./Public
COPY ./composer.json ./composer.json
COPY ./composer.lock ./composer.lock
COPY ./do ./do
COPY ./cube.php ./cube.php

RUN composer install

RUN chown -R www-data:www-data /var/www

EXPOSE 80
CMD ["apache2-foreground"]
